### ISSUE TITLE
Use current position instead of creating newline

### ISSUE THREAD

**Issue by jsonmaur** [helloIAmPau/node-spinner#16]
This is a great library, thanks for it!

Is it possible to show the spinner and title in the current cursor position rather than bumping it down to a new line? I have an instance where I have some text already outputted in the line with `process.stdout.write`, and when I start the spinner, it moves to a new line. Can I prevent this or is it not currently possible?

**Comment by jsonmaur** [comment]
And I'd also like to have the ability to only clear back to the original cursor position rather than clearing the entire line with `spinner.stop()`.

**Comment by helloIAmPau** [comment]
Hi @jsonmaur,
this library can't do that... for now :).
I'm planning to refactor the entire library and this can be a new feature I can add.

I tag this issue with the `enhancement` label and I'll try to keep it in mind :)
