### ISSUE TITLE
Not clear when execute a new console.log

### ISSUE THREAD

**Issue by jonatasfreitasv** [helloIAmPau/node-spinner#17]
With this code:

```
spinner.start();
console.log('Foo')
```

The result is: 

```
/ Foo
"spinner this"
```

Ever new console.log, some part of spinner continue in terminal, how I solve this !! 

thx

**Comment by mhulse** [comment]
See this as well. It clears if I put `spinner.stop(true);` before the `console.log(...)` but not after.
