### ISSUE TITLE
The spinner should disable itself if shell is not interactive

### ISSUE THREAD

**Issue by itamararjuan** [helloIAmPau/node-spinner#18]
This can be achieved easily by checking the following:

```js
if (require('tty').isatty(0)) 
{
  // interactive shell is active in here
}
```

**Comment by helloIAmPau** [comment]
I don't know if I want this feature.
The check should be in the module using the spinner. In a non-interactive shell, you should not create any spinner instance.

You can either try to convince me or close the issue :).
