### ISSUE TITLE
Animation stops when shelljs.exec or consolo.log is called

### ISSUE THREAD

**Issue by MarvinSzyperski** [helloIAmPau/node-spinner#33]
I want to use the spinner so the user knows something is loading, but in the case of a shell command the animation just freezes and that makes it useless in some of my usecases.
Is there a workaround or am I missing anything? 
Creating a childprocess and executing the command there doesnt help, as well as executing it in silent mode.
```
spinner.start()
shelljs.exec(my command that takes some seconds)
spinner.stop(true)
```
thanks already

**Comment by helloIAmPau** [comment]
can you please provide a code example of your issue?

**Comment by MarvinSzyperski** [comment]
This should create a node module in a previously specified folder with a required dependency
```
const spinner = new Spinner('initializing new Project %s'
spinner.setSpinnerString(19)
spinner.start()
shelljs.exec('npm init -y && npm i -D --save scc_types')
spinner.stop(true)
```
As those two commands might take a while, i want to use the spinner to show that it is still running. 
Instead the spinner appears but does not spin

**Comment by helloIAmPau** [comment]
Your problem here is you are using a "sync" version of shelljs.exec
You can think to reimplement your code like the following:
```
var Spinner = require('cli-spinner').Spinner;
var shelljs = require('shelljs');

const spinner = new Spinner('initializing new Project %s')
spinner.setSpinnerString(19)
spinner.start()
shelljs.exec('npm init -y && npm i -D --save scc_types', { silent: true }, function() {
        spinner.stop(true);
});
```
