### ISSUE TITLE
Spinner not appearing until stop called

### ISSUE THREAD

**Issue by jontonsoup** [helloIAmPau/node-spinner#8]
I'm having a flush error it seems -- the spinner doesn't show up until done is called. I'm calling start outside a promise and stop inside a promise for context. 

Best,
Jon

**Comment by helloIAmPau** [comment]
Please, give me a code example so that I can investigate on the issue.

**Comment by jontonsoup** [comment]
@helloIAmPau Let me dig up the code -- I'm using it in a couple projects and can't remember which one the bug was in. :)

**Comment by jontonsoup** [comment]
I fixed the wait by moving some `require` statements below the spinner start. False alarm :)

**Comment by helloIAmPau** [comment]
thank you for the notification!

bye :+1:
